# File loading demo:

In [31]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from ipywidgets import interact, widgets
import pickle
from os import listdir

def load_object(filename):
    with open(filename, 'rb') as  input:
        return pickle.load(input)

In [46]:
data = pd.DataFrame()

for experiment in listdir("saved_environments/"):
    for simulation in listdir("saved_environments/" + experiment + "/"):
        for player in load_object("saved_environments/" + experiment + "/" + simulation):
            data = pd.concat([data, pd.DataFrame([[experiment, simulation, 
                                                   player[0], player[1],
                                                   np.sum(player[2]), np.sum(player[2][1200:1500])]], 
                                                 columns=["experiment_id", "simulation_id", 
                                                         "player_id", "player_type",
                                                         "player_success", "success_last_300_steps"])], 
                             axis = 0)
data

,experiment_id,simulation_id,player_id,player_type,player_success,success_last_300_steps
0,experiment_test_1,three_simulation.pkl,1,Random Weights,1217,130
0,experiment_test_1,three_simulation.pkl,2,Thompsons,977,229
0,experiment_test_1,three_simulation.pkl,3,Thompsons discounted,1078,276
0,experiment_test_1,three_simulation.pkl,4,Thompsons,1090,220
0,experiment_test_1,three_simulation.pkl,5,Thompsons discounted,1590,281
0,experiment_test_1,three_simulation.pkl,6,Thompsons,425,64
0,experiment_test_1,three_simulation.pkl,7,Thompsons discounted,1023,233
0,experiment_test_1,another_simulation.pkl,1,Random Weights,1167,129
0,experiment_test_1,another_simulation.pkl,2,Thompsons,954,183
0,experiment_test_1,another_simulation.pkl,3,Thompsons discounted,579,134
0,experiment_test_1,another_simulation.pkl,4,Thompsons,1248,252
0,experiment_test_1,another_simulation.pkl,5,Thompsons discounted,1469,263
0,experiment_test_1,another_simulation.pkl,6,Thompsons,781,158
0,experiment_test_1,another_simulation.pkl,7,Thompsons discounted,1509,292
0,experiment_test_1,last_results.pkl,1,Random Weights,1471,202
0,experiment_test_1,last_results.pkl,2,Thompsons,1123,225
0,experiment_test_1,last_results.pkl,3,Thompsons discounted,470,59
0,experiment_test_1,last_results.pkl,4,Thompsons,412,63
0,experiment_test_1,last_results.pkl,5,Thompsons discounted,368,59
0,experiment_test_1,last_results.pkl,6,Thompsons,361,41
0,experiment_test_1,last_results.pkl,7,Thompsons discounted,1373,284
0,experiment_test_2,two_simulation.pkl,1,Random Weights,1183,131
0,experiment_test_2,two_simulation.pkl,2,Thompsons,1177,248
0,experiment_test_2,two_simulation.pkl,3,Thompsons discounted,454,99
0,experiment_test_2,two_simulation.pkl,4,Thompsons,1719,287
0,experiment_test_2,two_simulation.pkl,5,Thompsons discounted,876,204
0,experiment_test_2,two_simulation.pkl,6,Thompsons,1270,263
0,experiment_test_2,two_simulation.pkl,7,Thompsons discounted,819,127
0,experiment_test_2,one_simulation.pkl,1,Random Weights,1377,193
0,experiment_test_2,one_simulation.pkl,2,Thompsons,1041,198
0,experiment_test_2,one_simulation.pkl,3,Thompsons discounted,871,218
0,experiment_test_2,one_simulation.pkl,4,Thompsons,499,62
0,experiment_test_2,one_simulation.pkl,5,Thompsons discounted,1034,240
0,experiment_test_2,one_simulation.pkl,6,Thompsons,502,85
0,experiment_test_2,one_simulation.pkl,7,Thompsons discounted,373,56

   experiment_id  simulation_id  player_id     player_type  total_success
0              1              1          1  Random Weights   3.908946e+06