# File loading demo:

In [1]:
import numpy as np
import pandas as pd
#from ipywidgets import interact, widgets
import pickle
from os import listdir

def load_object(filename):
    with open(filename, 'rb') as  input:
        return pickle.load(input)

In [2]:
data = pd.DataFrame()

for experiment in listdir("saved_environments/"):
    for simulation in listdir("saved_environments/" + experiment + "/"):
        for player in load_object("saved_environments/" + experiment + "/" + simulation):
            data = pd.concat([data, pd.DataFrame([[experiment, simulation, 
                                                   player[0], player[1],
                                                   np.sum(player[2]),np.sum(player[2][:300]),
                                                   np.sum(player[2][1200:1500]), len(player[2])]], 
                                                 columns=["experiment_id", "simulation_id", 
                                                         "player_id", "player_type",
                                                         "player_success","success_first_300_steps", 
                                                          "success_last_300_steps", "timesteps"])], 
                             axis = 0)
data.to_pickle("raw_df.pkl")

In [5]:
"""plt.hist(data.player_success[(data.player_type == "UCB") & 
                             (data.experiment_id.str.contains('UT'))]/data.timesteps[(data.player_type == "UCB") & 
                                                                                     (data.experiment_id.str.contains('UT'))],
         bins = 100)"""
"""import statsmodels
statsmodels.graphics.gofplots.qqplot(data.player_success[(data.player_type == "UCB") & 
                             (data.experiment_id.str.contains('UT'))]/data.timesteps[(data.player_type == "UCB") & 
                                                                                     (data.experiment_id.str.contains('UT'))])"""

#data = data.reset_index()

data['normalized_success'] = data.player_success/data.timesteps

In [6]:
data.loc[data.timesteps == 5000, ['player_type', 'player_success', 'timesteps', 'success_last_300_steps']].groupby('player_type').mean()

                           player_success  timesteps  success_last_300_steps
player_type
CSMA                          2112.794167     5000.0              121.650000
Random                        1518.267500     5000.0               93.445833
Simulating Non-Static Env     3043.547312     5000.0              188.145161
Thompsons                     1942.412500     5000.0              116.978333
UCB                           3143.166667     5000.0              185.006818
UCB discounted                3590.584496     5000.0              222.222481

In [3]:
data.to_pickle("raw_df.pkl")

In [25]:
power = data.loc[data.timesteps == 5000, ['experiment_id', 
                                  'player_type', 
                                  'normalized_success']].groupby(['experiment_id', 
                                                                      'player_type']).var()
power['estimated_n'] = power.normalized_success * 9 /(.03**2)
#max(power.estimated_n[power.player_type != "CSMA"])
#power.loc[('UdU_0001111_ns', 'CSMA')]
power.iloc[(power.index.get_level_values('player_type') != 'CSMA') & 
           (power.index.get_level_values('player_type') != 'Simulating Non-Static Env') &
          (power.index.get_level_values('player_type') != 'Random')]

                               normalized_success  estimated_n
experiment_id  player_type
CT_0000001_ns  Thompsons                 0.022131   221.312633
CT_000111_ns   Thompsons                 0.017962   179.622144
CT_0111111_ns  Thompsons                 0.013248   132.479913
CU_0000001_ns  UCB                       0.018111   181.114255
CU_000111_ns   UCB                       0.022837   228.366823
CU_0111111_ns  UCB                       0.033479   334.792909
CUd_0000001_ns UCB discounted            0.000963     9.631165
CUd_000111_ns  UCB discounted            0.000602     6.023795
CUd_0111111_ns UCB discounted            0.020074   200.738625
RT_0000001_ns  Thompsons                 0.003793    37.934328
RT_000111_ns   Thompsons                 0.007101    71.013675
RT_0111111_ns  Thompsons                 0.010768   107.681459
RU_0000001_ns  UCB                       0.008697    86.971489
RU_000111_ns   UCB                       0.007040    70.397048
RU_0111111_ns  UCB                       0.025929   259.294722
RUd_0000001_ns UCB discounted            0.002164    21.636329
RUd_000111_ns  UCB discounted            0.002167    21.674045
RUd_0111111_ns UCB discounted            0.009769    97.685321
UT_0000001_ns  Thompsons                 0.023930   239.296537
               UCB                       0.036119   361.192947
UT_000111_ns   Thompsons                 0.012637   126.369607
               UCB                       0.006896    68.956766
UT_0111111_ns  Thompsons                 0.016976   169.759074
               UCB                       0.006218    62.179075
UUd_0000001_ns UCB                       0.025562   255.619784
               UCB discounted            0.022319   223.194502
UUd_000111_ns  UCB                       0.019799   197.991525
               UCB discounted            0.005352    53.524460
UUd_0111111_ns UCB                       0.011602   116.021846
               UCB discounted            0.017589   175.887803
UdT_0000001_ns Thompsons                 0.023004   230.040572
               UCB discounted            0.014707   147.070166
UdT_000111_ns  Thompsons                 0.019558   195.580860
               UCB discounted            0.003098    30.976488
UdT_0111111_ns Thompsons                 0.016739   167.385356
               UCB discounted            0.001826    18.260997
UdU_0001111_ns UCB                       0.014537   145.370836
               UCB discounted            0.013363   133.632497

In [1]:
data.loc[data.timesteps == 5000, ['experiment_id', 
                                  'player_type', 
                                  'player_success', 
                                  'timesteps', 
                                  'success_last_300_steps']].groupby(['experiment_id', 
                                                                      'player_type']).std()

NameError: name 'data' is not defined